---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mistral-app
  labels:
    name: mistral-app
    context: mistral-context
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mistral-app
        context: mistral-context
    spec:
      containers:
      - name: da
        image: bulankou/mistral:da
        ports:
          - containerPort: 8070
            hostPort: 8070
            name: http
      - name: mongo
        image: bulankou/mistral:mongo
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: mistral-service
  labels: 
    name: mistral-app
    context: mistral-context
spec: 
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8070
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: mistral-app
    context: mistral-context
---

